import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import type { ThemeMode } from "../context/ThemeContext";
import { useTheme } from "../hooks/useTheme";
import { api } from "../lib/api/endpoints";
import type { ModelConfig } from "../lib/api/types";
import {
  getWorkspacePreferences,
  resetWorkspacePreferences,
  updateWorkspacePreferences,
  type ComparisonMethod,
  type WorkspacePreferences,
} from "../lib/preferences";
import { storage } from "../lib/storage";

function methodLabel(method: ComparisonMethod): string {
  switch (method) {
    case "difflib":
      return "Fast compare";
    case "llm":
      return "Deep compare";
    default:
      return "Balanced";
  }
}

export function SettingsPage() {
  const navigate = useNavigate();
  const { theme, setTheme, toggleTheme } = useTheme();

  const [models, setModels] = useState<ModelConfig[]>([]);
  const [selectedModel, setSelectedModel] = useState<string>(storage.getSelectedModel() ?? "");
  const [loadingModels, setLoadingModels] = useState(true);
  const [modelError, setModelError] = useState<string | null>(null);

  const [preferences, setPreferences] = useState<WorkspacePreferences>(() => getWorkspacePreferences());

  useEffect(() => {
    let active = true;

    async function loadModels() {
      setLoadingModels(true);
      setModelError(null);

      try {
        const payload = await api.listModels();
        if (!active) {
          return;
        }

        setModels(payload.models);
        const fallbackModel = payload.recommended_model;
        const currentSelection = storage.getSelectedModel();
        const nextSelection = payload.models.some((model) => model.id === currentSelection)
          ? (currentSelection as string)
          : fallbackModel;

        setSelectedModel(nextSelection);
        storage.setSelectedModel(nextSelection);
      } catch {
        if (!active) {
          return;
        }
        setModelError("Could not load model metadata right now. Existing model preference will still work.");
      } finally {
        if (active) {
          setLoadingModels(false);
        }
      }
    }

    loadModels();

    return () => {
      active = false;
    };
  }, []);

  function applyPreference(patch: Partial<WorkspacePreferences>) {
    const updated = updateWorkspacePreferences(patch);
    setPreferences(updated);
  }

  function handleThemeChoice(nextTheme: ThemeMode) {
    setTheme(nextTheme);
  }

  function handleReset() {
    const defaults = resetWorkspacePreferences();
    setPreferences(defaults);
    setTheme("light");
  }

  return (
    <div className="settings-stage">
      <header className="settings-header">
        <button type="button" className="button button--ghost" onClick={() => navigate("/")}>Back to Chat</button>
        <div>
          <h1>Workspace Settings</h1>
          <p>Preferences save instantly and apply to new responses.</p>
        </div>
      </header>

      <div className="settings-grid">
        <section className="settings-card" aria-label="Assistant defaults">
          <h2>Assistant Defaults</h2>
          <p>Choose how answers are generated by default for this browser.</p>

          <label className="field">
            <span>Preferred model</span>
            <select
              value={selectedModel}
              disabled={loadingModels || models.length === 0}
              onChange={(event) => {
                const next = event.target.value;
                setSelectedModel(next);
                storage.setSelectedModel(next);
              }}
            >
              {models.map((model) => (
                <option key={model.id} value={model.id}>
                  {model.name} - {model.label}
                </option>
              ))}
            </select>
          </label>

          {modelError ? <p className="notice notice--error">{modelError}</p> : null}

          <label className="field">
            <span>Retrieval depth: {preferences.topK}</span>
            <input
              type="range"
              min={2}
              max={10}
              step={1}
              value={preferences.topK}
              onChange={(event) => applyPreference({ topK: Number(event.target.value) })}
            />
          </label>

          <label className="field">
            <span>Temporal compare style</span>
            <select
              value={preferences.comparisonMethod}
              onChange={(event) => applyPreference({ comparisonMethod: event.target.value as ComparisonMethod })}
            >
              <option value="both">Balanced (difflib + LLM)</option>
              <option value="difflib">Fast compare only</option>
              <option value="llm">Deep LLM compare only</option>
            </select>
          </label>
        </section>

        <section className="settings-card" aria-label="Reading preferences">
          <h2>Reading Experience</h2>
          <p>Reduce clutter or increase detail based on your working style.</p>

          <label className="switch-row">
            <input
              type="checkbox"
              checked={preferences.compactChat}
              onChange={(event) => applyPreference({ compactChat: event.target.checked })}
            />
            <span>Compact message layout</span>
          </label>

          <label className="switch-row">
            <input
              type="checkbox"
              checked={preferences.showTemporalDetails}
              onChange={(event) => applyPreference({ showTemporalDetails: event.target.checked })}
            />
            <span>Show temporal metadata panel in answers</span>
          </label>

          <label className="switch-row">
            <input
              type="checkbox"
              checked={preferences.showSourceSnippets}
              onChange={(event) => applyPreference({ showSourceSnippets: event.target.checked })}
            />
            <span>Expand source snippets by default</span>
          </label>
        </section>

        <section className="settings-card" aria-label="Appearance settings">
          <h2>Appearance</h2>
          <p>Pick a visual style suitable for your workspace environment.</p>

          <div className="theme-choice-group" role="group" aria-label="Theme options">
            <button
              type="button"
              className={`theme-choice ${theme === "light" ? "is-active" : ""}`}
              onClick={() => handleThemeChoice("light")}
            >
              Light
            </button>
            <button
              type="button"
              className={`theme-choice ${theme === "dark" ? "is-active" : ""}`}
              onClick={() => handleThemeChoice("dark")}
            >
              Dark
            </button>
            <button type="button" className="theme-choice" onClick={toggleTheme}>
              Toggle
            </button>
          </div>

          <div className="settings-actions">
            <button type="button" className="button" onClick={handleReset}>
              Reset to defaults
            </button>
            <button type="button" className="button button--primary" onClick={() => navigate("/")}>
              Return to chat
            </button>
          </div>
        </section>

        <section className="settings-card" aria-label="Current summary">
          <h2>Current Profile</h2>
          <div className="settings-pills">
            <span className="pill">Top-K {preferences.topK}</span>
            <span className="pill">{methodLabel(preferences.comparisonMethod)}</span>
            <span className="pill">{preferences.compactChat ? "Compact" : "Spacious"}</span>
            <span className="pill">{preferences.showTemporalDetails ? "Temporal On" : "Temporal Off"}</span>
            <span className="pill">{theme === "dark" ? "Dark Theme" : "Light Theme"}</span>
          </div>
        </section>
      </div>
    </div>
  );
}